// @flow
export default {
    CREATE_NEW_TICKET: 'CREATE_NEW_TICKET',
    CREATE_NEW_TICKET_SUCCESS: 'CREATE_NEW_TICKET_SUCCESS',

    GET_ALL_TICKETS: 'GET_ALL_TICKETS',
    GET_ALL_TICKETS_SUCCESS: 'GET_ALL_TICKETS_SUCCESS',

    GET_TICKET: 'GET_TICKET',

    DELETE_TICKET: 'DELETE_TICKET',
    DELETE_TICKET_SUCCESS: 'DELETE_TICKET_SUCCESS',

    EDIT_TICKET: 'EDIT_TICKET',
    EDIT_TICKET_SUCCESS: 'EDIT_TICKET_SUCCESS',

    GET_ERRORS: 'GET_ERRORS',

    SET_CURRENT_USER: 'SET_CURRENT_USER',

    REGISTER_USER: 'REGISTER_USER',
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    REGISTER_USER_FAIL: 'REGISTER_USER_FAIL',

    LOGIN: 'LOGIN'
}